let config = {

  "password_seed": {
    "ringneck": 42,
    "budgie": 43,
    "platycercus": 44,
    "cockatiel": 45,
    "personata": 46,
    "fischeri": 47,
    "roseicollis": 48,
    "plumhead": 49,
    "alexandrine": 50
  },

  "languages": {
    "budgie": "av_PERIQUITO",
    "platycercus": "av_ROSELA",
    "cockatiel": "av_CALOPSITA",
    "personata": "av_PERSONATA",
    "fischeri": "av_FISCHERI",
    "roseicollis": "av_ROSICOLOR",
    "plumhead": "av_CAMEIXA",
    "alexandrine": "av_GALEXANDRE",
    "ringneck": "av_RINGNECK"
  },

  "carousel_basepath": "https://arquivos-galpaodasaves.nyc3.cdn.digitaloceanspaces.com/imagens/calculadoras/",

  "carousel": {

    "ringneck": {
      "Verde": "1.png",
      "Azul": "2.png",
      "Cinza": "3.png",
      "Lutino": "4.png",
      "Albino": "5.png",
      "Azul Turquesa": "6.png",
      "Cleartail Azul Turquesa": "7.png",
      "Cleartail Opalino Esmeralda": "8.png",
      "Cleartail Opalino Violeta": "9.png",
      "sem nome": "10.png",
      "Cleartail Violeta": "11.png",
      "Buttercup Violeta Turquesa": "12.png",
      "Violeta Esmeralda": "13.png",
      "Violeta Turquesa": "14.png",
      "Opalino Azul Turquesa": "15.png",
      "Buttercup Violeta Turquesa": "16.png",
      "Diluído Verde": "17.png",
      "Alerquim Recessivo Violeta Índigo": "18.png",
      "Opalino Violeta Turquesa": "19.png",
      "sem nome 2": "20.png",
      "Violeta Esmeralda Índigo": "21.png",
      "sem nome 3": "22.png",
      "Pallid Azul": "23.png",
      "Pallid Violeta Índigo - Pallid Violeta": "24.png",
      "Cleartail Opalino Verde Violeta": "25.png",
      "Cleartail Azul": "26.png",
      "Alerquim Recessivo Verde": "27.png",
      "Pallid Violeta Índigo - Pallid Turquesa - Pallid Violeta": "28.png",
      "Opalino Azul": "29.png",
      "Azul Turquesa": "30.png",
      "Diluído Verde Violeta": "31.png",
      "Diluído Violeta Turquesa": "32.png",
      "Cleartail Opalino Verde - Cleartail Cinza": "33.png",
      "Opalino Lutino": "34.png",
      "Violeta": "35.png",
      "Opalino Azul Índigo - Cleartail Verde": "36.png",
      "Esmeralda Azul - Cobalto - Azul": "37.png",
      "Cleartail Opalino Violeta": "38.png",
      "Opalino Cobalto": "39.png",
      "Pallid Violeta": "40.png",
      "Cleartail Azul Índigo": "41.png",
      "Buttercup Azul Turquesa": "42.png",
      "Opalino Recessivo Cinza Índigo - Opalino Recessivo Azul Índigo": "43.png",
      "Cleartail Opalino Violeta Cobalto Turquesa": "44.png",
      "Opalino Dominante Esmeralda Azul": "45.png",
      "sem nome 4": "46.png",
      "Cinza Turquesa/Opalino/Recessivo - Opalino Recessivo Azul Índigo": "47.png",
      "Buttercup Azul Turquesa": "48.png",
      "Opalino Azul": "49.png",
      "Dominante Edged Violeta": "50.png",
      "Diluído Violeta Turquesa": "51.png",
      "Cleartail Verde": "52.png",
      "Buttercup Violeta Turquesa": "53.png",
      "Opalino Verde/Cleartail - Cleartail Opalino Verde Violeta": "54.png",
      "Buttercup Azul": "55.png",
      "Opalino Azul Turquesa": "56.png",
      "Cleartail Azul Índigo": "57.png",
      "Dominante Verde Violeta - Alerquim Recessivo Verde Violeta": "58.png",
      "Alerquim Recessivo Violeta Índigo": "59.png",
      "Alerquim Recessivo Azul": "60.png",
      "Cleartail Cobalto": "61.png",
      "Buttercup Violeta Turquesa - Cleartail Azul Turquesa": "62.png",
      "Alerquim Recessivo Azul Canela": "63.png",
      "Cleartail Violeta - Opalina Azul": "64.png",
      "Cleartail Violeta DF": "65.png",
      "Cleartail Azul Índigo": "66.png",
      "Opalino Recessivo Azul Índigo": "67.png",
      "Dominante Esmeralda Cobalto": "68.png",
      "Dominante Opalino Esmeralda Azul": "69.png",
      "Opalino Oliva": "70.png",
      "Opalino Cobalto": "71.png",
      "Opalino Malva - Opalino Oliva": "72.png",
      "Opalino Azul Turquesa": "73.png",
      "Violeta Edged": "74.png",
      "Diluído Verde": "75.png",
      "Cleartail Opalino Verde Violeta": "76.png",
      "Dominante Cobalto Índigo": "77.png",
      "Opalino Cinza": "78.png",
      "Cleartail Violeta": "79.png",
      "Opalino Violeta DF": "80.png",
      "Opalino Dominante Esmeralda Cobalto": "81.png",
      "Cleartail Opalino Verde Cinza": "82.png",
      "Azul Índigo": "83.png",
      "Opalino Dominante Esmeralda Azul/Recessivo": "84.png",
      "Diluído Dominante Edged Azul": "85.png",
      "Dominante Edged Verde Cinza": "86.png",
      "Opalino Recessivo Azul Turquesa": "87.png",
      "Recessivo Violeta": "88.png",
      "Cleartail Opalino Esmeralda Índigo": "89.png",
      "Cleartail Opalino Verde Violeta": "90.png",
      "Buttercup Cobalto": "91.png",
      "Dominante Esmeralda Violeta": "92.png",
      "Cleartail Violeta DF": "93.png",
      "Opalino Recessivo Azul Turquesa": "94.png",
      "Cleartail Opalino Azul Índigo": "95.png",
      "Buttercup Violeta Turquesa": "96.png",
      "Dominante Edged Verde Cinza": "97.png",
      "Cleartail Cinza": "98.png",
      "Dominante Azul Turquesa": "99.png",
      "Opalino Violeta Índigo": "100.png",
      "Buttercup Azul Turquesa": "101.png",
      "Pallid Violeta Índigo": "102.png",
      "Dominante Edged Verde Violeta": "103.png",
      "Buttercup Violeta Turquesa": "104.png",
      "Dominante Violeta": "105.png",
      "Alerquim Recessivo Violeta Índigo": "106.png",
      "Diluído Azul": "107.png",
      "Opalino Dominante Esmeralda Azul": "108.png",
      "Dominante Edged Verde": "109.png",
      "Diluído Dominante Edged Azul": "110.png",
      "Dominante Edged Azul Índigo": "111.png",
      "Dominante Esmeralda Violeta": "112.png",
      "Cinza Índigo": "113.png",
      "Pallid Diluído Verde": "114.png",
      "Violeta Canela": "115.png",
      "Dominante Esmeralda Violeta": "116.png",
      "Dominante Diluído Edged Azul": "117.png",
      "Buttercup Violeta": "118.png",
      "Opalino Verde Violeta": "119.png",
      "Pallid Cobalto Turquesa": "120.png",
      "Pallid Cobalto Índigo": "121.png",
      "Opalino Azul Turquesa": "122.png",
      "Buttercup Cinza": "123.png",
      "Buttercup Azul": "124.png",
      "Buttercup Violeta Turquesa": "125.png",
      "Pallid Esmeralda": "126.png",
      "Opalino Cobalto": "127.png",
      "Cleartail Malva Violeta": "128.png",
      "Buttercup Verde Jade": "129.png",
      "Cleartail Verde Cinza": "130.png",
      "Pallid Verde": "131.png",
      "Dominante Violeta DF": "132.png",
      "Opalino Cinza": "133.png",
      "Cleartail Cinza Turquesa": "134.png",
      "Alerquim Recessivo Violeta Cobalto": "135.png",
      "Buttercup Cobalto Índigo": "136.png",
      "Buttercup Cobalto": "137.png",
      "Cleartail Opalino Cobalto": "138.png",
      "Cleartail Opalino Verde": "139.png",
      "Opalino Esmeralda": "140.png",
      "Esmeralda Azul": "141.png",
      "Cremino": "142.png",
      "Cobalto": "143.png",
      "Verde Canela": "144.png",
      "Cleartail Violeta Esmeralda": "145.png"
    },

    "budgie": {
      'Verde Claro': 'PA_001_Verde_Claro.png',
      'Azul': 'PA_002_Azul.png',
      'Arlequim Dominante Holandes Verde Oliva': 'PA_0038_Arlequim_Dominante_Holandes_Verde_Oliva.png',
      'Verde Escuro': 'PA_003_Verde_Escuro.png',
      'Verde Oliva': 'PA_004_Verde_Oliva.png',
      'Verde Cinza': 'PA_005_Verde_Cinza.png',
      'Verde Claro Opalino': 'PA_006_Verde_Claro_Opalino.png',
      'Cinza': 'PA_007_Cinza.png',
      'Violeta': 'PA_008_Violeta.png',
      'Violeta Opalino': 'PA_009_Violeta_Opalino.png',
      'Violeta Face Amarela 2': 'PA_010_Violeta_Face_Amarela_2.png',
      'Violeta Opalino Face Amarela 2': 'PA_011_Violeta_Opalino_Face_Amarela_2.png',
      'Violeta Opalino Asas Cinzas': 'PA_012_Violeta_Opalino_Asas_Cinzas.png',
      'Violeta DF Opalino Asas Claras': 'PA_013_Violeta_DF_Opalino_Asas_Claras.png',
      'Lutino': 'PA_014_Lutino.png',
      'Albino': 'PA_015_Albino.png',
      'Cremino': 'PA_016_Cremino.png',
      'Verde Asa Canela': 'PA_017_Verde_Asa_Canela.png',
      'Azul Asa Canela': 'PA_018_Azul_Asa_Canela.png',
      'Cinza Asa Canela': 'PA_019_Cinza_Asa_Canela.png',
      'Cobalto Opalino Asa Canela': 'PA_020_Cobalto_Opalino_Asa_Canela.png',
      'Fallow Linha Azul': 'PA_021_Fallow_Linha_Azul.png',
      'Fallow Linha Verde': 'PA_022_Fallow_Linha_Verde.png',
      'Arco Iris Violeta Duplo Fator Golden Face': 'PA_023_Arco_Iris_Violeta_Duplo_Fator_Golden_Face.png',
      'Arco Iris Malva': 'PA_024_Arco_Iris_Malva.png',
      'Arco Iris Malva Golden Face': 'PA_025_Arco_Iris_Malva_Golden_Face.png',
      'Arco Iris Malva Violeta Golden Face Duplo Fator': 'PA_026_Arco_Iris_Malva_Violeta_Golden_Face_Duplo_Fator.png',
      'Arco Iris Cobalto Violeta Golden Face Duplo Fator': 'PA_027_Arco_Iris_Cobalto_Violeta_Golden_Face_Duplo_Fator.png',
      'Arco Iris Cobalto Violeta Opalino Asas Claras Golden Face': 'PA_028_Arco_Iris_Cobalto_Violeta_Opalino_Asas_Claras_Golden_Face.png',
      'Arco Iris Cobalto Face Amarela 2': 'PA_029_Arco_Iris_Cobalto_Face_Amarela_2.png',
      'Arco Iris Cobalto Violeta Face Amarela 2': 'PA_030_Arco_Iris_Cobalto_Violeta_Face_Amarela_2.png',
      'Arco Iris Celeste Violeta Face Amarela 2': 'PA_031_Arco_Iris_Celeste_Violeta_Face_Amarela_2.png',
      'Celeste Opalino Asas Claras': 'PA_032_Celeste_Opalino_Asas_Claras.png',
      'Arlequim Dominante Frosted Malva Violeta': 'PA_033_Arlequim_Dominante_Frosted_Malva_Violeta.png',
      'Arlequim Dominante Australiano Celeste Opalino Golden Face': 'PA_034_Arlequim_Dominante_Australiano_Celeste_Opalino_Golden_Face.png',
      'Arlequim Dominante Australiano Celeste Golden Face': 'PA_035_Arlequim_Dominante_Australiano_Celeste_Golden_Face.png',
      'Arlequim Dominante Australiano Cobalto Opalino': 'PA_036_Arlequim_Dominante_Australiano_Cobalto_Opalino.png',
      'Arlequim Dominante Holandes Opalino Violeta Asa Canela': 'PA_037_Arlequim_Dominante_Holandes_Opalino_Violeta_Asa_Canela.png',
      'Arlequim Recessivo Opalino Cobalto Face Amarela 2': 'PA_039_Arlequim_Recessivo_Opalino_Cobalto_Face_Amarela_2.png',
      'Arlequim Recessivo Corpo Claro do Texas Cinza Opalino': 'PA_040_Arlequim_Recessivo_Corpo_Claro_do_Texas_Cinza_Opalino.png',
      'Arlequim Recessivo Cobalto Opalino': 'PA_041_Arlequim_Recessivo_Cobalto_Opalino.png',
      'Arlequim Recessivo Cobalto Violeta Opalino': 'PA_042_Arlequim_Recessivo_Cobalto_Violeta_Opalino.png',
      'Arlequim Recessivo Duplo Fator Golden Face': 'PA_043_Arlequim_Recessivo_Duplo_Fator_Golden_Face.png',
      'Arlequim Recessivo Celeste Golden Face': 'PA_044_Arlequim_Recessivo_Celeste_Golden_Face.png',
      'Celeste Opalino Fullbody Face Amarela 2': 'PA_045_Celeste_Opalino_Fullbody_Face_Amarela_2.png',
      'Celeste Opalino Asas Claras Golden Face': 'PA_046_Celeste_Opalino_Asas_Claras_Golden_Face.png',
      'Corpo Claro do Texas Asas Claras': 'PA_047_Corpo_Claro_do_Texas_Asas_Claras.png',
      'Corpo Claro do Texas Malva Opalino': 'PA_048_Corpo_Claro_do_Texas_Malva_Opalino.png',
      'Corpo Claro do Texas Malva Asa Canela': 'PA_049_Corpo_Claro_do_Texas_Malva_Asa_Canela.png',
      'Corpo Claro do Texas Celeste Opalino': 'PA_050_Corpo_Claro_do_Texas_Celeste_Opalino.png',
      'Corpo Claro do Texas Violeta Opalino': 'PA_051_Corpo_Claro_do_Texas_Violeta_Opalino.png',
      'Corpo Claro do Texas Cobalto Violeta Opalino': 'PA_052_Corpo_Claro_do_Texas_Cobalto_Violeta_Opalino.png', 'Corpo Claro do Texas Cobalto Face Amarela 2': 'PA_053_Corpo_Claro_do_Texas_Cobalto_Face_Amarela_2.png', 'Corpo Claro do Texas Cinza Face Amarela 2': 'PA_059_Corpo_Claro_do_Texas_Cinza_Face_Amarela_2.png', 'Corpo Claro do Texas Cinza Opalino': 'PA_055_Corpo_Claro_do_Texas_Cinza_Opalino.png', 'Corpo Claro do Texas Cinza Opalino Asas Cinzas': 'PA_056_Corpo_Claro_do_Texas_Cinza_Opalino_Asas_Cinzas.png', 'Corpo Claro do Texas Cinza Opalino Face Amarela 2': 'PA_057_Corpo_Claro_do_Texas_Cinza_Opalino_Face_Amarela_2.png', 'Corpo Claro do Texas Opalino Asa Canela Cobalto Violeta Golden Face': 'PA_058_Corpo_Claro_do_Texas_Opalino_Asa_Canela_Cobalto_Violeta_Golden_Face.png', 'Corpo Claro do Texas Celeste Opalino Face Amarela 2': 'PA_060_Corpo_Claro_do_Texas_Celeste_Opalino_Face_Amarela_2.png', 'Corpo Claro do Texas Verde Oliva Opalino': 'PA_061_Corpo_Claro_do_Texas_Verde_Oliva_Opalino.png', 'Corpo Claro do Texas Verde Cinza': 'PA_062_Corpo_Claro_do_Texas_Verde_Cinza.png', 'Corpo Claro do Texas Verde Cinza Opalino': 'PA_063_Corpo_Claro_do_Texas_Verde_Cinza_Opalino.png', 'Corpo Claro do Texas Verde Escuro': 'PA_064_Corpo_Claro_do_Texas_Verde_Escuro.png', 'Corpo Claro do Texas Verde Escuro Opalino': 'PA_065_Corpo_Claro_do_Texas_Verde_Escuro_Opalino.png', 'Corpo Claro do Texas Verde Opalino Asas Cinzas': 'PA_066_Corpo_Claro_do_Texas_Verde_Opalino_Asas_Cinzas.png', 'Corpo Claro do Texas Verde Cinza Opalino Asas Cinzas': 'PA_067_Corpo_Claro_do_Texas_Verde_Cinza_Opalino_Asas_Cinzas.png', 'Corpo Claro do Texas Verde Claro Asa Canela': 'PA_068_Corpo_Claro_do_Texas_Verde_Claro_Asa_Canela.png', 'Fulvo Normal Celeste Golden Face': 'PA_069_Fulvo_Normal_Celeste_Golden_Face.png', 'mao Opalino Malva Violeta Golden Face Duplo Fator': 'Alemao_Opalino_Malva_Violeta_Golden_Face_Duplo_Fator.png', 'mao Normal Violeta Duplo Fator Golden Face DF': 'Alemao_Normal_Violeta_Duplo_Fator_Golden_Face_DF.png', 'Fulvo Malva Violeta Golden Face Duplo Fator': 'PA_073_Fulvo_Malva_Violeta_Golden_Face_Duplo_Fator.png', 'Quimera Asas Claras (Halfsider)': 'PA_074_Quimera_Asas_Claras_(Halfsider).png', 'Rendado': 'PA_075_Rendado.png', 'Cintilante Celeste': 'PA_076_Cintilante_Celeste.png', 'Cintilante Duplo Fator Linha Azul': 'PA_077_Cintilante_Duplo_Fator_Linha_Azul.png'
    },

    "platycercus": {
      'Ancestral': 'RE_001_Ancestral.png',
      'Azul': 'RE_002_Azul.png',
      'Manto Dourado': 'RE_003_Manto_Dourado.png',
      'Pastel': 'RE_004_Pastel.png',
      'Diluído': 'RE_005_Diluido.png',
      'Black': 'RE_006_Black.png',
      'Arlequim Dominante': 'RE_010_Arlequim_Dominante.png',
      'Golden': 'RE_008_Golden.png',
      'Arlequim Dominante Asa Branca Pastel': 'RE_009_Arlequim_Dominante_Asa_Branca_Pastel.png',
      'Edged Dominante Diluído': 'RE_044_Edged_Dominante_Diluido.png',
      'Yellow Headed': 'RE_030_Yellow_Headed.png',
      'Rubina': 'RE_013_Rubina.png',
      'Opalina': 'RE_014_Opalina.png',
      'Canela': 'RE_015_Canela.png',
      'Lutina': 'RE_016_Lutina.png',
      'Azul Edged Pastel': 'RE_017_Azul_Edged_Pastel.png',
      'Azul Edged Dominante': 'RE_018_Azul_Edged_Dominante.png',
      'Manto Dourado Diluído': 'RE_019_Manto_Dourado_Diluido.png',
      'Canela Diluído': 'RE_020_Canela_Diluido.png',
      'Opalino Canela': 'RE_022_Opalino_Canela.png',
      'Canela Edged Dominante': 'RE_023_Canela_Edged_Dominante.png',
      'Opalino Canela Diluído': 'RE_024_Opalino_Canela_Diluido.png',
      'Turquesa Lutino Diluído': 'RE_025_Turquesa_Lutino_Diluido.png',
      'Canela Diluído Edged Dominante': 'RE_026_Canela_Diluido_Edged_Dominante.png',
      'Lutino Canela': 'RE_027_Lutino_Canela.png',
      'Rubino Canela': 'RE_028_Rubino_Canela.png',
      'Lutino Arlequim': 'RE_029_Lutino_Arlequim.png',
      'Black Opalina': 'RE_031_Black_Opalina.png',
      'Black Lutino': 'RE_032_Black_Lutino.png',
      'Black Rubino': 'RE_033_Black_Rubino.png',
      'Black Canela': 'RE_034_Black_Canela.png',
      'Black Diluído': 'RE_035_Black_Diluido.png',
      'Black Opalino Diluído': 'RE_036_Black_Opalino_Diluido.png',
      'Black Opalino Canela': 'RE_037_Black_Opalino_Canela.png',
      'Black Arlequim': 'RE_038_Black_Arlequim.png',
      'Opalino Diluído': 'RE_039_Opalino_Diluido.png',
      'Opalino Arlequim': 'RE_040_Opalino_Arlequim.png',
      'Opalino Edged Dominante Diluído': 'RE_041_Opalino_Edged_Dominante_Diluido.png',
      'Yellow Headed Opalino': 'RE_042_Yellow_Headed_Opalino.png',
      'Yellow Headed Lutino': 'RE_043_Yellow_Headed_Lutino.png',
      'Edged Dominante Opalino': 'RE_045_Edged_Dominante_Opalino.png',
      'Turquesa Canela': 'RE_O21_Turquesa_Canela.png'
    },

    "cockatiel": {
      'Silvestre, Ancestral ou Cinza Cara Amarela': 'CL_001_Silvestre,_Ancestral_ou_Cinza_Cara_Amarela.png',
      'Lutino': 'CL_002_Lutino.png',
      'Canela': 'CL_003_Canela.png', 'Cara Branca': 'CL_004_Cara_Branca.png', 'Esmeralda': 'CL_005_Esmeralda.png', 'Opalino': 'CL_006_Opalino.png', 'Lutino Opalino': 'CL_007_Lutino_Opalino.png', 'Lutino Canela': 'CL_008_Lutino_Canela.png', 'Lutino Arlequim': 'CL_009_Lutino_Arlequim.png', 'Lutino Cara Branca (Albino)': 'CL_010_Lutino_Cara_Branca_(Albino).png', 'Arlequim Reverso Opalino Pastel Face': 'CL_011_Arlequim_Reverso_Opalino_Pastel_Face.png', 'Arlequim Reverso Opalino Cara Amarela': 'CL_012_Arlequim_Reverso_Opalino_Cara_Amarela.png', 'Arlequim Reverso Canela Cara Amarela': 'CL_013_Arlequim_Reverso_Canela_Cara_Amarela.png', 'Arlequim Reverso Cara Branca': 'CL_014_Arlequim_Reverso_Cara_Branca.png', 'Arlequim Reverso Opalino Canela Pastel Face': 'CL_015_Arlequim_Reverso_Opalino_Canela_Pastel_Face.png', 'Arlequim Reverso Opalino Canela Cara Amarela': 'CL_016_Arlequim_Reverso_Opalino_Canela_Cara_Amarela.png', 'Arlequim Reverso Canela Cara Branca': 'CL_017_Arlequim_Reverso_Canela_Cara_Branca.png', 'Arlequim Opalina Cream Face': 'CL_018_Arlequim_Opalina_Cream_Face.png', 'Arlequim Opalino Cara Amarela': 'CL_019_Arlequim_Opalino_Cara_Amarela.png', 'Arlequim Opalino Canela': 'CL_020_Arlequim_Opalino_Canela.png', 'Arlequim Opalino Cara Branca': 'CL_021_Arlequim_Opalino_Cara_Branca.png', 'Arlequim Canela Cara Branca': 'CL_022_Arlequim_Canela_Cara_Branca.png', 'Arlequim Cinza Cara Branca': 'CL_023_Arlequim_Cinza_Cara_Branca.png', 'Arlequim Clear Cara Amarela': 'CL_024_Arlequim_Clear_Cara_Amarela.png', 'Fulvo Bronze Cara Branca': 'CL_025_Fulvo_Bronze_Cara_Branca.png', 'Fulvo Bronze Cara Amarela': 'CL_026_Fulvo_Bronze_Cara_Amarela.png', 'Opalino Canela': 'CL_027_Opalino_Canela.png', 'Opalino Canela Cara Branca': 'CL_028_Opalino_Canela_Cara_Branca.png', 'Opalino Cara Branca': 'CL_029_Opalino_Cara_Branca.png', 'Opalino Pastel Face': 'CL_030_Opalino_Pastel_Face.png', 'Opalina Canela Pastel Face': 'CL_031_Opalina_Canela_Pastel_Face.png', 'Opalina Cream Face': 'CL_032_Opalina_Cream_Face.png', 'Prata Recessivo Opalino Cara Branca': 'CL_033_Prata_Recessivo_Opalino_Cara_Branca.png', 'Prata Recessivo Cara Branca': 'CL_034_Prata_Recessivo_Cara_Branca.png', 'Prata Recessivo Opalino Canela Pastel Face': 'CL_035_Prata_Recessivo_Opalino_Canela_Pastel_Face.png', 'Prata Recessivo Opalino Pastel Face': 'CL_036_Prata_Recessivo_Opalino_Pastel_Face.png', 'Prata Dominante': 'CL_037_Prata_Dominante.png', 'Prata Dominante Pastel Face': 'CL_038_Prata_Dominante_Pastel_Face.png'
    },

    "personata": {
      'Jade': 'AP_001_Jade.png', 'Verde Violeta': 'AP_002_Verde_Violeta.png', 'Verde Oliva': 'AP_003_Verde_Oliva.png', 'Verde Diluido': 'AP_004_Verde_Diluido.png', 'Jade Diluido': 'AP_005_Jade_Diluido.png', 'Lutino': 'AP_006_Lutino.png', 'Golden Verde': 'AP_007_Golden_Verde.png', 'Golden Jade': 'AP_008_Golden_Jade.png', 'Golden Violeta': 'AP_009_Golden_Violeta.png', 'Arlequim Verde': 'AP_010_Arlequim_Verde.png', 'Arlequim Violeta Verde': 'AP_011_Arlequim_Violeta_Verde.png', 'Albino': 'AP_012_Albino.png', 'Azul': 'AP_013_Azul.png', 'Cobalto': 'AP_014_Cobalto.png', 'Azul Diluido': 'AP_015_Azul_Diluido.png', 'Cobalto Diluido': 'AP_016_Cobalto_Diluido.png', 'Silver Simples Fator Azul': 'AP_017_Silver_Simples_Fator_Azul.png', 'Silver Duplo Fator Azul': 'AP_018_Silver_Duplo_Fator_Azul.png', 'Silver Cobalto Simples Fator': 'AP_019_Silver_Cobalto_Simples_Fator.png', 'Malva': 'AP_020_Malva.png', 'Malva Diluido': 'AP_021_Malva_Diluido.png', 'Arlequim Violeta': 'AP_024_Arlequim_Violeta.png', 'Violeta': 'AP_025_Violeta.png', 'Silver Violeta': 'AP_026_Silver_Violeta.png', 'Violeta Diluido': 'AP_027_Violeta_Diluido.png', '22 Silver Duplo Fator Cobalto': 'AP_22_Silver_Duplo_Fator_Cobalto.png', '23 Arlequim Cobalto': 'AP_23_Arlequim_Cobalto.png'
    },

    "fischeri": {
      'Verde': 'AF_001_Verde.png', 'Verde Diluido': 'AF_002_Verde_Diluido.png', 'Verde Jade': 'AF_003_Verde_Jade.png', 'Jade Diluido': 'AF_004_Jade_Diluido.png', 'Oliva': 'AF_005_Oliva.png', 'Oliva Diluido': 'AF_006_Oliva_Diluido.png', 'Verde Diluido Ino': 'AF_007_Verde_Diluido_Ino.png', 'Lutino': 'AF_008_Lutino.png', 'Amarelo de Olhos Pretos DEC': 'AF_009_Amarelo_de_Olhos_Pretos_DEC.png', 'Golden Jade': 'AF_010_Golden_Jade.png', 'Golden Verde Duplo Fator': 'AF_011_Golden_Verde_Duplo_Fator.png', 'Golden Oliva': 'AF_012_Golden_Oliva.png', 'Arlequim Verde': 'AF_013_Arlequim_Verde.png', 'Arlequim Jade': 'AF_014_Arlequim_Jade.png', 'Arlequim Oliva': 'AF_015_Arlequim_Oliva.png', 'Verde Violeta': 'AF_016_Verde_Violeta.png', 'Albino': 'AF_017_Albino.png', 'Azul': 'AF_018_Azul.png', 'Azul Diluido': 'AF_019_Azul_Diluido.png', 'Cobalto': 'AF_020_Cobalto.png', 'Cobalto Diluido': 'AF_021_Cobalto_Diluido.png', 'Malva': 'AF_022_Malva.png', 'Malva Diluido': 'AF_023_Malva_Diluido.png', 'Silver Azul': 'AF_024_Silver_Azul.png', 'Silver Cobalto': 'AF_025_Silver_Cobalto.png', 'Arlequim Azul': 'AF_026_Arlequim_Azul.png', 'Arlequim Cobalto': 'AF_027_Arlequim_Cobalto.png', 'Arlequim Malva': 'AF_028_Arlequim_Malva.png', 'Silver Violeta': 'AF_029_Silver_Violeta.png', 'Violeta': 'AF_030_Violeta.png', 'Arlequim Violeta': 'AF_031_Arlequim_Violeta.png'
    },

    "roseicollis": {
      'Silver Acqua Cobalto': 'AR_001_Silver_Acqua_Cobalto.png', 
      'Silver Acqua Azul': 'AR_002_Silver_Acqua_Azul.png',
      'Arlequim Acqua Turquesa': 'AR_003_Arlequim_Acqua_Turquesa.png',
      'Arlequim Acqua Violeta': 'AR_004_Arlequim_Acqua_Violeta.png',
      'Arlequim Verde Jade': 'AR_005_Arlequim_Verde_Jade.png',
      'Face Laranja Canela Australiano':'AR_006_Face_Laranja_Canela_Australiano.png',
      'Golden Jade': 'AR_007_Golden_Jade.png',
      'Verde Ancestral': 'AR_008_Verde_Ancestral.png',
      'Fulvo Acqua Turquesa Malva': 'AR_009_Fulvo_Acqua_Turquesa_Malva.png',
      'Verde Oliva DD ou Verde Violeta': 'AR_010_Verde_Oliva_DD_ou_Verde_Violeta.png',
      'Verde Oliva Opalino ou Verde DD Face Vermelha': 'AR_011_Verde_Oliva_Opalino_ou_Verde_DD_Face_Vermelha.png',
      'Lutino Opalino Face Vermelha': 'AR_012_Lutino_Opalino_Face_Vermelha.png',
      'Cremino Turquesa': 'AR_013_Cremino_Turquesa.png', 'Fulvo Face Vermelha': 'AR_014_Fulvo_Face_Vermelha.png', 'Silver Japonês Acqua Violeta': 'AR_015_Silver_Japonês_Acqua_Violeta.png', 'Face Laranja Verde Jade': 'AR_016_Face_Laranja_Verde_Jade.png', 'Silver Turquesa Malva': 'AR_017_Silver_Turquesa_Malva.png', 'Canela Americano Oliva': 'AR_018_Canela_Americano_Oliva.png', 'Australiano Face Branca': 'AR_019_Australiano_Face_Branca.png', 'Branco Australiano Acqua Azul': 'AR_020_Branco_Australiano_Acqua_Azul.png', 'Canela Americano Verde': 'AR_021_Canela_Americano_Verde.png', 'Arlequim Turquesa': 'AR_022_Arlequim_Turquesa.png', 'Pallid Verde': 'AR_023_Pallid_Verde.png', 'Cremino Face Branca': 'AR_024_Cremino_Face_Branca.png', 'Cremino Acqua': 'AR_025_Cremino_Acqua.png', 'Turquesa': 'AR_026_Turquesa.png', 'Turquesa Cobalto': 'AR_027_Turquesa_Cobalto.png', 'Acqua Canela': 'AR_028_Acqua_Canela.png', 'Violeta Turquesa': 'AR_029_Violeta_Turquesa.png', 'Face Branca Malva': 'AR_030_Face_Branca_Malva.png', 'Face Laranja Arlequim Violeta': 'AR_031_Face_Laranja_Arlequim_Violeta.png', 'Silver Turquesa': 'AR_032_Silver_Turquesa.png', 'Face Laranja Golden': 'AR_033_Face_Laranja_Golden.png', 'Face Laranja Canela Americano Jade': 'AR_034_Face_Laranja_Canela_Americano_Jade.png', 'Pallid Oliva': 'AR_035_Pallid_Oliva.png', 'Silver Acqua Malva': 'AR_036_Silver_Acqua_Malva.png', 'Face Laranja Golden Verde': 'AR_037_Face_Laranja_Golden_Verde.png', 'Face Vermelha Pallid Jade': 'AR_038_Face_Vermelha_Pallid_Jade.png', 'Face Laranja Lutino': 'AR_039_Face_Laranja_Lutino.png', 'Face Laranja Oliva': 'AR_040_Face_Laranja_Oliva.png', 'Arlequim Azul Depurado': 'AR_041_Arlequim_Azul_Depurado.png', 'Violeta Duplo Fator Depurado': 'AR_042_Violeta_Duplo_Fator_Depurado.png', 'Canela Americano Violeta Depurado': 'AR_043_Canela_Americano_Violeta_Depurado.png', 'Arlequim Violeta Turquesa': 'AR_044_Arlequim_Violeta_Turquesa.png', 'Fulvo Violeta Depurado': 'AR_045_Fulvo_Violeta_Depurado.png', 'Opalino Violeta Simples Fator Depurado': 'AR_046_Opalino_Violeta_Simples_Fator_Depurado.png', 'Opalino Cobalto Depurado': 'AR_047_Opalino_Cobalto_Depurado.png', 'Canela Americano Azul Depurado': 'AR_048_Canela_Americano_Azul_Depurado.png', 'Azul Depurado': 'AR_049_Azul_Depurado.png', 'Albino (Azul Ino)': 'AR_050_Albino_(Azul_Ino).png'
    },

    "plumhead": {
      'Azul': 'CA_000_Azul.png', 'Verde Ancestral': 'CA_001_Verde_Ancestral.png', 'Verde Cinza': 'CA_002_Verde_Cinza.png', 'Lutino': 'CA_003_Lutino.png', 'Diluido': 'CA_004_Diluido.png', 'Azul Opalino': 'CA_006_Azul_Opalino.png', 'Turquesa': 'CA_007_Turquesa.png', 'Verde Cinza Canela': 'CA_008_Verde_Cinza_Canela.png', 'Verde Canela': 'CA_009_Verde_Canela.png', 'Verde Cinza Opalino': 'CA_010_Verde_Cinza_Opalino.png', 'Verde Opalino': 'CA_011_Verde_Opalino.png', 'Verde Pastel': 'CA_012_Verde_Pastel.png', 'Verde Cinza Diluído': 'CA_013_Verde_Cinza_Diluído.png', 'Verde Cinza Pastel Opalino': 'CA_014_Verde_Cinza_Pastel_Opalino.png', 'Pastel Diluido': 'CA_015_Pastel_Diluido.png', 'Arlequim Dominante': 'CA_016_Arlequim_Dominante.png', 'Opalino Diluido': 'CA_017_Opalino_Diluido.png', 'Arlequim Recessivo': 'CA_018_Arlequim_Recessivo.png'
    },
    
    "alexandrine": {
      'Verde': 'GA_001_Verde.png', 'Azul': 'GA_002_Azul.png', 'Albino': 'GA_003_Albino.png', 'Albino Cinza Recessivo': 'GA_004_Albino_Cinza_Recessivo.png', 'Turquesa': 'GA_005_Turquesa.png', 'Cinza': 'GA_006_Cinza.png', 'Violeta': 'GA_007_Violeta.png', 'Cobalto': 'GA_008_Cobalto.png', 'Cleartail Azul': 'GA_009_Cleartail_Azul.png', 'Arlequim Dominante Azul': 'GA_010_Arlequim_Dominante_Azul.png', 'Esmeralda': 'GA_011_Esmeralda.png', 'Lutino': 'GA_012_Lutino.png', 'Arlequim Recessivo Verde': 'GA_013_Arlequim_Recessivo_Verde.png', 'Diluido Verde': 'GA_014_Diluido_Verde.png', 'Oliva': 'GA_015_Oliva.png', 'Pallid Verde': 'GA_016_Pallid_Verde.png', 'Bronze Fallow': 'GA_017_Bronze_Fallow.png', 'Bronze': 'GA_018_Bronze.png', 'Canela': 'GA_019_Canela.png', 'Verde Violeta DF': 'GA_020_Verde_Violeta_DF.png', 'Verde Violeta SF': 'GA_021_Verde_Violeta_SF.png', 'Verde Violeta Arlequim Dominante': 'GA_022_Verde_Violeta_Arlequim_Dominante.png', 'Buttercup Verde': 'GA_023_Buttercup_Verde.png', 'Buttercup Verde Jade': 'GA_024_Buttercup_Verde_Jade.png', 'Verde Cinza': 'GA_025_Verde_Cinza.png'
    }

  },

};

